/**
 * Export module — XLSX (Phase 4a) and print-to-PDF (Phase 4b).
 * Uses the existing xlsx (SheetJS) dependency; no extra packages needed.
 */
import * as XLSX from "xlsx";
import type { PnlReport, BalanceSheetReport, CashFlowReport } from "./reportDerived";

const fmt = (n: number) =>
  new Intl.NumberFormat("en-IN", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(n);

const DISCLAIMER =
  "Generated by MeeshoProfit — for internal use only. Not a certified financial statement.";

// ── Helpers ───────────────────────────────────────────────────────────

type Row = (string | number)[];

function sectionHeader(title: string): Row {
  return [title];
}

function line(label: string, value: number, indent = false): Row {
  return [indent ? `    ${label}` : label, value];
}

function totalLine(label: string, value: number): Row {
  return [`*** ${label}`, value];
}

function blankRow(): Row {
  return [""];
}

function autoFit(ws: XLSX.WorkSheet, rows: Row[]): void {
  ws["!cols"] = [
    { wch: Math.max(45, ...rows.map((r) => String(r[0] ?? "").length + 4)) },
    { wch: 18 },
  ];
}

// ── Phase 4a: XLSX Export ─────────────────────────────────────────────

export function exportPnlToXlsx(report: PnlReport): void {
  const rows: Row[] = [
    [`${report.orgName} — Profit & Loss Statement`],
    [`Period: ${report.from} to ${report.to}  |  Basis: ${report.view === "accrual" ? "Accrual" : "Cash"}`],
    [DISCLAIMER],
    blankRow(),
    sectionHeader("INCOME"),
    line("Sales Revenue (Delivered)", report.income.sales, true),
    line("Exchange Income", report.income.exchangeIncome, true),
    line("Claims & Compensation", report.income.claimsComp, true),
    line("Lost Order Compensation", report.income.lostComp, true),
    totalLine("TOTAL REVENUE", report.income.totalRevenue),
    blankRow(),
    sectionHeader("COST OF GOODS SOLD"),
    line("Cost of Goods Sold", report.expenses.cogs, true),
    totalLine("GROSS PROFIT", report.grossProfit),
    blankRow(),
    sectionHeader("OPERATING EXPENSES"),
    line("Return & RTO Losses", report.expenses.returnLosses, true),
    line("Platform & Affiliate Fees", report.expenses.platformFees, true),
    line("Advertising", report.expenses.advertising, true),
    line("QC Damage Write-offs", report.expenses.qcWriteoffs, true),
    line("Operating Expenses", report.expenses.operatingExpenses, true),
    totalLine("TOTAL OPERATING EXPENSES", report.expenses.totalExpenses),
    blankRow(),
    totalLine("NET PROFIT", report.netProfit),
    line(`Net Margin`, report.netMarginPct / 100, true),
    blankRow(),
    sectionHeader("TAX CREDITS (RECEIVABLE FROM GOI)"),
    line("TDS Receivable", report.recoverable.tds, true),
    line("TCS Receivable", report.recoverable.tcs, true),
  ];

  const ws = XLSX.utils.aoa_to_sheet(rows);

  // Format margin row as percentage
  const marginCell = XLSX.utils.encode_cell({ r: rows.length - 4, c: 1 });
  if (ws[marginCell]) ws[marginCell].z = "0.00%";

  autoFit(ws, rows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "P&L");
  XLSX.writeFile(wb, `PnL_${report.from}_to_${report.to}.xlsx`);
}

export function exportBalanceSheetToXlsx(report: BalanceSheetReport): void {
  const rows: Row[] = [
    [`${report.orgName} — Balance Sheet`],
    [`As of ${report.asOf}`],
    [DISCLAIMER],
    blankRow(),
    sectionHeader("ASSETS"),
    sectionHeader("  Current Assets"),
    line("Cash & Bank Receipts", report.assets.cash, true),
    line("Accounts Receivable", report.assets.accountsReceivable, true),
    line("Inventory", report.assets.inventory, true),
    line("TDS Receivable", report.assets.tdsReceivable, true),
    line("TCS Receivable", report.assets.tcsReceivable, true),
    totalLine("TOTAL CURRENT ASSETS", report.assets.totalCurrentAssets),
    totalLine("TOTAL ASSETS", report.assets.totalAssets),
    blankRow(),
    sectionHeader("LIABILITIES"),
    sectionHeader("  Current Liabilities"),
    line("Accounts Payable", report.liabilities.accountsPayable, true),
    totalLine("TOTAL LIABILITIES", report.liabilities.totalLiabilities),
    blankRow(),
    sectionHeader("EQUITY"),
    line("Retained Earnings", report.equity.retainedEarnings, true),
    totalLine("TOTAL EQUITY", report.equity.totalEquity),
    blankRow(),
    totalLine("TOTAL LIABILITIES & EQUITY", report.totalLiabilitiesAndEquity),
    blankRow(),
    report.balanced
      ? ["✓ Balance sheet is balanced"]
      : [`⚠ Imbalance: ₹${fmt(Math.abs(report.imbalance))} — ${report.imbalanceNote}`],
  ];

  const ws = XLSX.utils.aoa_to_sheet(rows);
  autoFit(ws, rows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Balance Sheet");
  XLSX.writeFile(wb, `BalanceSheet_${report.asOf}.xlsx`);
}

export function exportCashFlowToXlsx(report: CashFlowReport): void {
  const rows: Row[] = [
    [`${report.orgName} — Cash Flow Statement (Indirect Method)`],
    [`Period: ${report.from} to ${report.to}`],
    [DISCLAIMER],
    blankRow(),
    sectionHeader("OPERATING ACTIVITIES"),
    line("Net Profit", report.operating.netProfit, true),
    sectionHeader("  Adjustments for non-cash items:"),
    line("QC Damage Write-offs", report.operating.addQcWriteoffs, true),
    sectionHeader("  Working capital movements:"),
    line("(Increase)/Decrease in Accounts Receivable", report.operating.arChange, true),
    line("Increase/(Decrease) in Accounts Payable", report.operating.apChange, true),
    totalLine("CASH FROM OPERATING ACTIVITIES", report.operating.total),
    ["  Note: " + report.operating.note],
    blankRow(),
    sectionHeader("INVESTING ACTIVITIES"),
    line("Purchase of Inventory (cash paid)", report.investing.purchasePayments, true),
    totalLine("CASH FROM INVESTING ACTIVITIES", report.investing.total),
    blankRow(),
    sectionHeader("FINANCING ACTIVITIES"),
    line("No tracked financing activities", 0, true),
    totalLine("CASH FROM FINANCING ACTIVITIES", report.financing.total),
    blankRow(),
    totalLine("NET CHANGE IN CASH", report.netCashChange),
  ];

  const ws = XLSX.utils.aoa_to_sheet(rows);
  autoFit(ws, rows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Cash Flow");
  XLSX.writeFile(wb, `CashFlow_${report.from}_to_${report.to}.xlsx`);
}

export function exportAllReportsToXlsx(
  pnl: PnlReport,
  bs: BalanceSheetReport,
  cf: CashFlowReport
): void {
  const wb = XLSX.utils.book_new();

  // P&L sheet
  const pnlRows: Row[] = [
    [`${pnl.orgName} — Profit & Loss Statement`],
    [`Period: ${pnl.from} to ${pnl.to}  |  Basis: ${pnl.view === "accrual" ? "Accrual" : "Cash"}`],
    blankRow(),
    sectionHeader("INCOME"),
    line("Sales Revenue (Delivered)", pnl.income.sales, true),
    line("Exchange Income", pnl.income.exchangeIncome, true),
    line("Claims & Compensation", pnl.income.claimsComp, true),
    line("Lost Order Compensation", pnl.income.lostComp, true),
    totalLine("TOTAL REVENUE", pnl.income.totalRevenue),
    blankRow(),
    line("Cost of Goods Sold", pnl.expenses.cogs, true),
    totalLine("GROSS PROFIT", pnl.grossProfit),
    blankRow(),
    sectionHeader("OPERATING EXPENSES"),
    line("Return & RTO Losses", pnl.expenses.returnLosses, true),
    line("Platform & Affiliate Fees", pnl.expenses.platformFees, true),
    line("Advertising", pnl.expenses.advertising, true),
    line("QC Damage Write-offs", pnl.expenses.qcWriteoffs, true),
    line("Operating Expenses", pnl.expenses.operatingExpenses, true),
    totalLine("TOTAL EXPENSES", pnl.expenses.totalExpenses),
    blankRow(),
    totalLine("NET PROFIT", pnl.netProfit),
    blankRow(),
    [DISCLAIMER],
  ];
  const pnlWs = XLSX.utils.aoa_to_sheet(pnlRows);
  autoFit(pnlWs, pnlRows);
  XLSX.utils.book_append_sheet(wb, pnlWs, "P&L");

  // Balance Sheet sheet
  const bsRows: Row[] = [
    [`${bs.orgName} — Balance Sheet as of ${bs.asOf}`],
    blankRow(),
    sectionHeader("ASSETS"),
    line("Cash & Bank Receipts", bs.assets.cash, true),
    line("Accounts Receivable", bs.assets.accountsReceivable, true),
    line("Inventory", bs.assets.inventory, true),
    line("TDS Receivable", bs.assets.tdsReceivable, true),
    line("TCS Receivable", bs.assets.tcsReceivable, true),
    totalLine("TOTAL ASSETS", bs.assets.totalAssets),
    blankRow(),
    sectionHeader("LIABILITIES"),
    line("Accounts Payable", bs.liabilities.accountsPayable, true),
    totalLine("TOTAL LIABILITIES", bs.liabilities.totalLiabilities),
    blankRow(),
    sectionHeader("EQUITY"),
    line("Retained Earnings", bs.equity.retainedEarnings, true),
    totalLine("TOTAL EQUITY", bs.equity.totalEquity),
    blankRow(),
    totalLine("TOTAL LIABILITIES & EQUITY", bs.totalLiabilitiesAndEquity),
    blankRow(),
    [DISCLAIMER],
  ];
  const bsWs = XLSX.utils.aoa_to_sheet(bsRows);
  autoFit(bsWs, bsRows);
  XLSX.utils.book_append_sheet(wb, bsWs, "Balance Sheet");

  // Cash Flow sheet
  const cfRows: Row[] = [
    [`${cf.orgName} — Cash Flow Statement (Indirect Method)`],
    [`Period: ${cf.from} to ${cf.to}`],
    blankRow(),
    line("Net Profit", cf.operating.netProfit, true),
    line("+ QC Write-offs (non-cash)", cf.operating.addQcWriteoffs, true),
    line("± AR Change", cf.operating.arChange, true),
    line("± AP Change", cf.operating.apChange, true),
    totalLine("CASH FROM OPERATIONS", cf.operating.total),
    blankRow(),
    line("Inventory Purchases (cash paid)", cf.investing.purchasePayments, true),
    totalLine("CASH FROM INVESTING", cf.investing.total),
    blankRow(),
    totalLine("NET CASH CHANGE", cf.netCashChange),
    blankRow(),
    [DISCLAIMER],
  ];
  const cfWs = XLSX.utils.aoa_to_sheet(cfRows);
  autoFit(cfWs, cfRows);
  XLSX.utils.book_append_sheet(wb, cfWs, "Cash Flow");

  XLSX.writeFile(wb, `FinancialReports_${pnl.from}_to_${pnl.to}.xlsx`);
}

// ── Phase 4b: Print-to-PDF ────────────────────────────────────────────

export function printReport(title: string): void {
  const prev = document.title;
  document.title = title;
  window.print();
  document.title = prev;
}
