"use client";
/**
 * Financial Reports — Phase 1–4
 * P&L · Balance Sheet · Cash Flow with XLSX + print-to-PDF export.
 *
 * Reports are derived from V2State (no server, no backfill needed).
 * Standard: informal internal use — footer disclaimer on every export.
 */
import { useMemo, useState } from "react";
import {
  AlertCircle,
  CheckCircle2,
  Download,
  FileSpreadsheet,
  Printer,
  TrendingDown,
  TrendingUp,
} from "lucide-react";
import { useV2 } from "@/book/lib/v2/store";
import { Guard, PageHeader } from "@/book/components/v2/common";
import { Badge, Button, Card, cn } from "@/book/components/ui";
import { formatINR } from "@/book/lib/engine";
import {
  pnlReport,
  balanceSheet,
  cashFlowStatement,
  reportMonthOptions,
  PnlReport,
  BalanceSheetReport,
  CashFlowReport,
} from "@/book/lib/v2/reportDerived";
import type { PnlFilter } from "@/book/lib/v2/derived";
import {
  exportPnlToXlsx,
  exportBalanceSheetToXlsx,
  exportCashFlowToXlsx,
  exportAllReportsToXlsx,
  printReport,
} from "@/book/lib/v2/exportReports";

type Tab = "pnl" | "balance" | "cashflow";
type PnlView = "accrual" | "cash";

const DISCLAIMER =
  "Generated by MeeshoProfit · For internal use only · Not a certified financial statement";

// ── Small layout helpers ──────────────────────────────────────────────

function SectionHead({ title }: { title: string }) {
  return (
    <tr className="print:break-inside-avoid">
      <td colSpan={2} className="pb-1 pt-4">
        <span className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
          {title}
        </span>
      </td>
    </tr>
  );
}

function LineRow({
  label,
  value,
  indent = false,
  bold = false,
  tone,
}: {
  label: string;
  value: number;
  indent?: boolean;
  bold?: boolean;
  tone?: "positive" | "negative" | "neutral";
}) {
  const colorClass =
    tone === "positive"
      ? "text-success"
      : tone === "negative"
      ? "text-danger"
      : "";
  return (
    <tr className="border-b border-border/40 last:border-0 print:break-inside-avoid">
      <td className={cn("py-1.5 text-sm", indent && "pl-6", bold && "font-semibold")}>
        {label}
      </td>
      <td
        className={cn(
          "py-1.5 text-right tabular-nums text-sm",
          bold && "font-semibold",
          colorClass
        )}
      >
        {formatINR(value, true)}
      </td>
    </tr>
  );
}

function TotalRow({
  label,
  value,
  tone,
  thick = false,
}: {
  label: string;
  value: number;
  tone?: "positive" | "negative" | "neutral";
  thick?: boolean;
}) {
  const colorClass =
    tone === "positive"
      ? "text-success"
      : tone === "negative"
      ? "text-danger"
      : "";
  return (
    <tr
      className={cn(
        "print:break-inside-avoid",
        thick ? "border-y-2 border-foreground/30" : "border-t border-border"
      )}
    >
      <td className="py-2 text-sm font-bold">{label}</td>
      <td className={cn("py-2 text-right tabular-nums text-sm font-bold", colorClass)}>
        {formatINR(value, true)}
      </td>
    </tr>
  );
}

function Divider() {
  return (
    <tr>
      <td colSpan={2} className="py-1" />
    </tr>
  );
}

// ── P&L Report ────────────────────────────────────────────────────────

function PnlView({ report }: { report: PnlReport }) {
  const marginTone =
    report.netMarginPct >= 15
      ? "positive"
      : report.netMarginPct >= 0
      ? "neutral"
      : "negative";

  return (
    <table className="w-full border-collapse">
      <tbody>
        <SectionHead title="Income" />
        <LineRow label="Sales Revenue (Delivered)" value={report.income.sales} indent />
        {report.income.exchangeIncome > 0 && (
          <LineRow label="Exchange Income" value={report.income.exchangeIncome} indent />
        )}
        {report.income.claimsComp > 0 && (
          <LineRow label="Claims & Compensation" value={report.income.claimsComp} indent />
        )}
        {report.income.lostComp > 0 && (
          <LineRow label="Lost Order Compensation" value={report.income.lostComp} indent />
        )}
        <TotalRow label="Total Revenue" value={report.income.totalRevenue} tone="positive" />

        <Divider />
        <SectionHead title="Cost of Goods Sold" />
        <LineRow label="Cost of Goods Sold (COGS)" value={report.expenses.cogs} indent />
        <TotalRow
          label="Gross Profit"
          value={report.grossProfit}
          tone={report.grossProfit >= 0 ? "positive" : "negative"}
        />

        <Divider />
        <SectionHead title="Operating Expenses" />
        <LineRow label="Return & RTO Losses" value={report.expenses.returnLosses} indent />
        <LineRow label="Platform & Affiliate Fees" value={report.expenses.platformFees} indent />
        <LineRow label="Advertising" value={report.expenses.advertising} indent />
        {report.expenses.qcWriteoffs > 0 && (
          <LineRow label="QC Damage Write-offs" value={report.expenses.qcWriteoffs} indent />
        )}
        <LineRow label="Operating Expenses" value={report.expenses.operatingExpenses} indent />
        <TotalRow label="Total Operating Expenses" value={report.expenses.totalExpenses} tone="negative" />

        <Divider />
        <TotalRow
          label="Net Profit"
          value={report.netProfit}
          tone={report.netProfit >= 0 ? "positive" : "negative"}
          thick
        />
        <tr>
          <td className="py-1 text-xs text-muted-foreground">Net Margin</td>
          <td
            className={cn(
              "py-1 text-right text-xs font-semibold",
              marginTone === "positive"
                ? "text-success"
                : marginTone === "negative"
                ? "text-danger"
                : "text-muted-foreground"
            )}
          >
            {report.netMarginPct.toFixed(1)}%
          </td>
        </tr>

        {(report.recoverable.tds > 0 || report.recoverable.tcs > 0) && (
          <>
            <Divider />
            <SectionHead title="Tax Credits (Receivable from GoI)" />
            {report.recoverable.tds > 0 && (
              <LineRow label="TDS Deducted by Meesho (Receivable)" value={report.recoverable.tds} indent />
            )}
            {report.recoverable.tcs > 0 && (
              <LineRow label="TCS Collected by Meesho (Receivable)" value={report.recoverable.tcs} indent />
            )}
          </>
        )}
      </tbody>
    </table>
  );
}

// ── Balance Sheet ─────────────────────────────────────────────────────

function BalanceSheetView({ report }: { report: BalanceSheetReport }) {
  return (
    <>
      {!report.balanced && (
        <div className="mb-4 flex items-start gap-2 rounded-xl bg-warning/10 p-3 text-sm text-warning print:hidden">
          <AlertCircle className="mt-0.5 h-4 w-4 shrink-0" />
          <span>
            <strong>Sheet not in balance</strong> (difference ₹{Math.abs(report.imbalance).toFixed(2)}).{" "}
            {report.imbalanceNote}
          </span>
        </div>
      )}
      {report.balanced && (
        <div className="mb-4 flex items-center gap-2 rounded-xl bg-success/10 p-3 text-sm text-success print:hidden">
          <CheckCircle2 className="h-4 w-4 shrink-0" />
          Balance sheet is balanced — Assets = Liabilities + Equity
        </div>
      )}

      <div className="grid gap-6 lg:grid-cols-2 print:grid-cols-2">
        {/* Assets */}
        <div>
          <table className="w-full border-collapse">
            <tbody>
              <SectionHead title="Assets" />
              <SectionHead title="Current Assets" />
              <LineRow label="Cash & Bank Receipts" value={report.assets.cash} indent />
              <LineRow label="Accounts Receivable" value={report.assets.accountsReceivable} indent />
              <LineRow label="Inventory" value={report.assets.inventory} indent />
              {report.assets.tdsReceivable > 0 && (
                <LineRow label="TDS Receivable" value={report.assets.tdsReceivable} indent />
              )}
              {report.assets.tcsReceivable > 0 && (
                <LineRow label="TCS Receivable" value={report.assets.tcsReceivable} indent />
              )}
              <TotalRow label="Total Current Assets" value={report.assets.totalCurrentAssets} />
              <Divider />
              <TotalRow label="Total Assets" value={report.assets.totalAssets} tone="positive" thick />
            </tbody>
          </table>
        </div>

        {/* Liabilities + Equity */}
        <div>
          <table className="w-full border-collapse">
            <tbody>
              <SectionHead title="Liabilities" />
              <SectionHead title="Current Liabilities" />
              <LineRow label="Accounts Payable" value={report.liabilities.accountsPayable} indent />
              <TotalRow label="Total Current Liabilities" value={report.liabilities.totalCurrentLiabilities} />
              <Divider />
              <TotalRow label="Total Liabilities" value={report.liabilities.totalLiabilities} />

              <Divider />
              <SectionHead title="Equity" />
              <LineRow label="Retained Earnings (Cumulative Net Profit)" value={report.equity.retainedEarnings} indent />
              <TotalRow label="Total Equity" value={report.equity.totalEquity} />

              <Divider />
              <TotalRow
                label="Total Liabilities & Equity"
                value={report.totalLiabilitiesAndEquity}
                tone="neutral"
                thick
              />
            </tbody>
          </table>
        </div>
      </div>

      <p className="mt-4 text-xs text-muted-foreground">
        Cash is estimated from Meesho settlement receipts minus paid expenses and purchases.
        Inventory is valued at weighted-average COGS × closing stock units.
        Imbalances typically reflect owner equity or opening inventory not yet configured.
      </p>
    </>
  );
}

// ── Cash Flow Statement ───────────────────────────────────────────────

function CashFlowView({ report }: { report: CashFlowReport }) {
  return (
    <>
      <table className="w-full border-collapse">
        <tbody>
          <SectionHead title="Operating Activities (Indirect Method)" />
          <LineRow label="Net Profit (from P&L)" value={report.operating.netProfit} indent bold />
          <SectionHead title="Adjustments for Non-Cash Items" />
          <LineRow label="QC Damage Write-offs" value={report.operating.addQcWriteoffs} indent />
          <SectionHead title="Working Capital Movements" />
          <LineRow
            label="(Increase) / Decrease in Accounts Receivable"
            value={report.operating.arChange}
            indent
            tone={report.operating.arChange >= 0 ? "positive" : "negative"}
          />
          <LineRow
            label="Increase / (Decrease) in Accounts Payable"
            value={report.operating.apChange}
            indent
            tone={report.operating.apChange >= 0 ? "positive" : "negative"}
          />
          <TotalRow
            label="Cash from Operating Activities"
            value={report.operating.total}
            tone={report.operating.total >= 0 ? "positive" : "negative"}
            thick
          />

          <Divider />
          <SectionHead title="Investing Activities" />
          <LineRow
            label="Purchase of Inventory (cash paid)"
            value={report.investing.purchasePayments}
            indent
            tone={report.investing.purchasePayments <= 0 ? "negative" : "neutral"}
          />
          <TotalRow
            label="Cash from Investing Activities"
            value={report.investing.total}
            tone={report.investing.total >= 0 ? "positive" : "negative"}
          />

          <Divider />
          <SectionHead title="Financing Activities" />
          <LineRow label="No tracked financing activities" value={0} indent />
          <TotalRow label="Cash from Financing Activities" value={0} />

          <Divider />
          <TotalRow
            label="Net Change in Cash"
            value={report.netCashChange}
            tone={report.netCashChange >= 0 ? "positive" : "negative"}
            thick
          />
        </tbody>
      </table>

      <p className="mt-4 text-xs text-muted-foreground">
        {report.operating.note}
      </p>
    </>
  );
}

// ── Main Page ─────────────────────────────────────────────────────────

export default function ReportsPage() {
  const { state } = useV2();
  const [tab, setTab] = useState<Tab>("pnl");
  const [view, setView] = useState<PnlView>("accrual");

  const monthOptions = useMemo(() => reportMonthOptions(state), [state]);
  const defaultFrom = monthOptions[0]?.value ?? "";
  const defaultTo = monthOptions[monthOptions.length - 1]?.value ?? "";

  const [fromMonth, setFromMonth] = useState(defaultFrom);
  const [toMonth, setToMonth] = useState(defaultTo);

  // Sync defaults when state changes (first import)
  const effectiveFrom = fromMonth || defaultFrom;
  const effectiveTo = toMonth || defaultTo;
  const today = new Date().toISOString().slice(0, 10);

  const filter: PnlFilter = { fromMonth: effectiveFrom, toMonth: effectiveTo, view };

  const pnl = useMemo(() => {
    if (!effectiveFrom) return null;
    return pnlReport(state, filter);
  }, [state, effectiveFrom, effectiveTo, view]); // eslint-disable-line react-hooks/exhaustive-deps

  const bs = useMemo(() => balanceSheet(state, today), [state, today]); // eslint-disable-line react-hooks/exhaustive-deps
  const cf = useMemo(() => {
    if (!effectiveFrom) return null;
    return cashFlowStatement(state, filter);
  }, [state, effectiveFrom, effectiveTo, view]); // eslint-disable-line react-hooks/exhaustive-deps

  const hasData = monthOptions.length > 0;

  function handleExcelExport() {
    if (!pnl || !cf) return;
    if (tab === "pnl") exportPnlToXlsx(pnl);
    else if (tab === "balance") exportBalanceSheetToXlsx(bs);
    else if (tab === "cashflow") exportCashFlowToXlsx(cf);
  }

  function handleAllExport() {
    if (!pnl || !cf) return;
    exportAllReportsToXlsx(pnl, bs, cf);
  }

  function handlePdfExport() {
    const titles: Record<Tab, string> = {
      pnl: `P&L Statement ${effectiveFrom} to ${effectiveTo}`,
      balance: `Balance Sheet as of ${today}`,
      cashflow: `Cash Flow Statement ${effectiveFrom} to ${effectiveTo}`,
    };
    printReport(titles[tab]);
  }

  const tabConfig: { id: Tab; label: string }[] = [
    { id: "pnl", label: "Profit & Loss" },
    { id: "balance", label: "Balance Sheet" },
    { id: "cashflow", label: "Cash Flow" },
  ];

  return (
    <Guard section="reports">
      {/* Print-only header — hidden in UI */}
      <div className="hidden print:block print:mb-6">
        <p className="text-2xl font-bold">
          {tab === "pnl"
            ? "Profit & Loss Statement"
            : tab === "balance"
            ? "Balance Sheet"
            : "Cash Flow Statement"}
        </p>
        <p className="text-sm text-muted-foreground">
          {state.org.name || "My Business"} ·{" "}
          {tab === "balance"
            ? `As of ${today}`
            : `${effectiveFrom} to ${effectiveTo}`}
        </p>
        <p className="mt-1 text-xs text-muted-foreground">{DISCLAIMER}</p>
        <hr className="mt-3 border-border" />
      </div>

      {/* Normal header — hidden when printing */}
      <div className="print:hidden">
        <PageHeader
          title="Financial Reports"
          sub="P&L, Balance Sheet, and Cash Flow — derived from your imported orders and purchases."
          right={
            <div className="flex gap-2">
              <Button variant="secondary" onClick={handlePdfExport} disabled={!hasData}>
                <Printer className="h-4 w-4" />
                <span className="hidden sm:inline">PDF</span>
              </Button>
              <Button variant="secondary" onClick={handleExcelExport} disabled={!hasData}>
                <FileSpreadsheet className="h-4 w-4" />
                <span className="hidden sm:inline">Excel</span>
              </Button>
              <Button onClick={handleAllExport} disabled={!hasData}>
                <Download className="h-4 w-4" />
                <span className="hidden sm:inline">All Reports</span>
              </Button>
            </div>
          }
        />
      </div>

      {!hasData ? (
        <Card className="p-8 text-center text-muted-foreground">
          <p className="font-medium">No data yet.</p>
          <p className="mt-1 text-sm">Import your order CSV and payment XLSX from Integrations to generate reports.</p>
        </Card>
      ) : (
        <>
          {/* Filters — hidden when printing */}
          <Card className="mb-5 flex flex-wrap items-center gap-3 p-4 print:hidden">
            {/* Date range */}
            <div className="flex items-center gap-2 text-sm">
              <span className="text-muted-foreground">From</span>
              <select
                value={effectiveFrom}
                onChange={(e) => setFromMonth(e.target.value)}
                className="rounded-lg border border-border bg-background px-2 py-1 text-sm"
              >
                {monthOptions.map((m) => (
                  <option key={m.value} value={m.value}>{m.label}</option>
                ))}
              </select>
              <span className="text-muted-foreground">To</span>
              <select
                value={effectiveTo}
                onChange={(e) => setToMonth(e.target.value)}
                className="rounded-lg border border-border bg-background px-2 py-1 text-sm"
              >
                {monthOptions.map((m) => (
                  <option key={m.value} value={m.value}>{m.label}</option>
                ))}
              </select>
            </div>

            {/* Accrual / Cash toggle (only relevant for P&L and Cash Flow) */}
            {tab !== "balance" && (
              <div className="flex rounded-lg border border-border text-sm">
                <button
                  className={cn(
                    "px-3 py-1 rounded-l-lg",
                    view === "accrual"
                      ? "bg-primary text-primary-foreground font-medium"
                      : "text-muted-foreground hover:bg-muted"
                  )}
                  onClick={() => setView("accrual")}
                >
                  Accrual
                </button>
                <button
                  className={cn(
                    "px-3 py-1 rounded-r-lg border-l border-border",
                    view === "cash"
                      ? "bg-primary text-primary-foreground font-medium"
                      : "text-muted-foreground hover:bg-muted"
                  )}
                  onClick={() => setView("cash")}
                >
                  Cash
                </button>
              </div>
            )}

            {tab === "balance" && (
              <Badge tone="info" className="ml-auto">
                As of today · {today}
              </Badge>
            )}
          </Card>

          {/* Tab bar — hidden when printing */}
          <div className="mb-5 flex gap-1 rounded-xl border border-border bg-muted p-1 print:hidden">
            {tabConfig.map(({ id, label }) => (
              <button
                key={id}
                onClick={() => setTab(id)}
                className={cn(
                  "flex-1 rounded-lg px-3 py-2 text-sm font-medium transition-colors",
                  tab === id
                    ? "bg-background shadow text-foreground"
                    : "text-muted-foreground hover:text-foreground"
                )}
              >
                {label}
              </button>
            ))}
          </div>

          {/* Report card */}
          <Card className="overflow-hidden">
            {/* Card header */}
            <div className="flex flex-wrap items-start justify-between gap-2 border-b border-border bg-muted/30 px-5 py-4 print:border-0 print:bg-transparent print:p-0 print:pb-4">
              <div>
                <p className="font-semibold">
                  {tab === "pnl"
                    ? "Profit & Loss Statement"
                    : tab === "balance"
                    ? "Balance Sheet"
                    : "Cash Flow Statement (Indirect Method)"}
                </p>
                <p className="text-sm text-muted-foreground">
                  {state.org.name || "My Business"} ·{" "}
                  {tab === "balance"
                    ? `As of ${today}`
                    : `${effectiveFrom} to ${effectiveTo} · ${view === "accrual" ? "Accrual" : "Cash"} basis`}
                </p>
              </div>

              {/* Quick net profit badge for P&L */}
              {tab === "pnl" && pnl && (
                <div
                  className={cn(
                    "flex items-center gap-1.5 rounded-xl px-3 py-2 text-sm font-semibold",
                    pnl.netProfit >= 0
                      ? "bg-success/10 text-success"
                      : "bg-danger/10 text-danger"
                  )}
                >
                  {pnl.netProfit >= 0 ? (
                    <TrendingUp className="h-4 w-4" />
                  ) : (
                    <TrendingDown className="h-4 w-4" />
                  )}
                  {formatINR(pnl.netProfit, true)} net profit
                </div>
              )}
            </div>

            {/* Report body */}
            <div className="p-5">
              {tab === "pnl" && pnl && <PnlView report={pnl} />}
              {tab === "balance" && <BalanceSheetView report={bs} />}
              {tab === "cashflow" && cf && <CashFlowView report={cf} />}
            </div>

            {/* Footer disclaimer */}
            <div className="border-t border-border px-5 py-3 print:border-t print:mt-4">
              <p className="text-xs text-muted-foreground">{DISCLAIMER}</p>
            </div>
          </Card>

          {/* Mobile export row — shown below card on small screens */}
          <div className="mt-4 flex gap-2 print:hidden sm:hidden">
            <Button variant="secondary" className="flex-1" onClick={handlePdfExport}>
              <Printer className="h-4 w-4" /> PDF
            </Button>
            <Button variant="secondary" className="flex-1" onClick={handleExcelExport}>
              <FileSpreadsheet className="h-4 w-4" /> Excel
            </Button>
          </div>
        </>
      )}
    </Guard>
  );
}
