/**
 * Invoice PDF (Phase 3) — clean single-page document via pdf-lib (already a
 * dependency). Invoices are single-amount documents today (no line items), so
 * the body is a summary table: amount, received, credited, balance due.
 *
 * Note: pdf-lib's standard fonts are WinAnsi-encoded and cannot draw "₹"
 * (U+20B9) — amounts are rendered as "Rs 1,234.56".
 */
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { Customer, Invoice, Org } from "../v2/types";

function rs(n: number): string {
  return `Rs ${n.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export interface InvoicePdfArgs {
  org: Pick<Org, "name" | "gstin" | "state">;
  invoice: Invoice;
  customer?: Customer;
}

export async function buildInvoicePdf({ org, invoice, customer }: InvoicePdfArgs): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([595, 842]); // A4 portrait
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const ink = rgb(0.13, 0.15, 0.19);
  const dim = rgb(0.45, 0.48, 0.53);
  const line = rgb(0.85, 0.87, 0.9);
  const M = 48; // margin
  let y = 794;

  const text = (s: string, x: number, size = 10, f = font, color = ink) =>
    page.drawText(s, { x, y, size, font: f, color });
  const right = (s: string, size = 10, f = font, color = ink) =>
    page.drawText(s, { x: 595 - M - f.widthOfTextAtSize(s, size), y, size, font: f, color });
  const rule = () => page.drawLine({ start: { x: M, y: y }, end: { x: 595 - M, y: y }, thickness: 0.7, color: line });

  // Header
  text(org.name || "My Business", M, 18, bold);
  right("INVOICE", 18, bold, dim);
  y -= 16;
  if (org.gstin) { text(`GSTIN ${org.gstin}`, M, 9, font, dim); }
  if (org.state) { y -= 12; text(org.state, M, 9, font, dim); }
  y -= 22; rule();

  // Meta block
  y -= 24;
  text("Invoice no.", M, 9, font, dim); text(invoice.number || invoice.id, M + 70, 10, bold);
  right(`Date  ${invoice.invoiceDate}`, 10);
  y -= 16;
  right(`Due  ${invoice.dueDate}`, 10);

  // Bill to
  y -= 30;
  text("BILL TO", M, 8, bold, dim);
  y -= 14;
  text(customer?.name ?? "Customer", M, 12, bold);
  for (const l of [customer?.gstin && `GSTIN ${customer.gstin}`, customer?.address, customer?.state, customer?.phone, customer?.email].filter(Boolean) as string[]) {
    y -= 13;
    text(l, M, 9, font, dim);
  }

  // Amount table
  y -= 34; rule();
  y -= 18;
  text("DESCRIPTION", M, 8, bold, dim); right("AMOUNT", 8, bold, dim);
  y -= 16;
  text(invoice.notes?.trim() || "Goods / services", M, 10);
  right(rs(invoice.amount), 10);
  y -= 14; rule();

  // Summary
  const credited = invoice.amountCredited ?? 0;
  const balance = Math.round((invoice.amount - invoice.amountPaid - credited) * 100) / 100;
  const row = (label: string, val: string, emph = false) => {
    y -= 16;
    const f = emph ? bold : font;
    page.drawText(label, { x: 360, y, size: emph ? 11 : 9.5, font: f, color: emph ? ink : dim });
    page.drawText(val, { x: 595 - M - f.widthOfTextAtSize(val, emph ? 11 : 9.5), y, size: emph ? 11 : 9.5, font: f, color: ink });
  };
  row("Invoice total", rs(invoice.amount));
  if (invoice.amountPaid > 0.005) row("Received", `- ${rs(invoice.amountPaid)}`);
  if (credited > 0.005) row("Credit notes", `- ${rs(credited)}`);
  y -= 6;
  page.drawLine({ start: { x: 360, y }, end: { x: 595 - M, y }, thickness: 0.7, color: line });
  row("Balance due", rs(Math.max(0, balance)), true);

  // Status + footer
  y -= 28;
  text(invoice.status === "paid" ? "PAID — thank you!" : `Status: ${invoice.status.toUpperCase()}`, M, 10, bold,
    invoice.status === "paid" ? rgb(0.09, 0.55, 0.35) : dim);
  page.drawText("Generated by Tulmin Book", { x: M, y: 40, size: 8, font, color: dim });

  return doc.save();
}
